### ISSUE TITLE
How to set options in ModelForm?

### ISSUE THREAD

**Issue by KrunchMuffin** [benmurden/django-intl-tel-input#13]
Trying to figure out how to set the options in a ModelForm
I tried this

        widgets = {
            'company_phone': IntlTelInputWidget(visible_input_attrs={
                'class': 'form-control',
                'preferred-countries':
                    ['us', 'ca']
                }),

I tried this, but doesn't seem correct even though it works.

    self.fields['company_phone'].widget.attrs['data-preferred-countries'] = ['us', 'ca']

end up with this

    <input type="tel" name="company_phone_0" size="30" class="js-intl-tel-input form-control 
    intltelinput" data-allow-dropdown="" data-auto-hide-dial-code="" data-auto-placeholder="polite" 
    data-dropdown-container="" data-exclude-countries="[]" data-format-on-display="" data-initial-
    country="" data-national-mode="" data-placeholder-number-type="MOBILE" data-only-countries="[]" 
    data-preferred-countries="['us', 'gb']" preferred_countries="['us', 'ca']" separate_dialcode="" 
    maxlength="15" required="" id="id_company_phone_0" autocomplete="off" placeholder="(201) 555-0123">

**Comment by benmurden** [comment]
Thanks for taking the time to write out your process. Looks like we need some better documentation.

In the meantime, check out the form declaration used in the tests. https://github.com/benmurden/django-intl-tel-input/blob/1cc6e1263e8b1b09d322ca90733ba588086c3b3f/testapp/forms.py#L10-L15

You'll see the widget should be initialized as follows
```Python
widgets = {
    'company_phone': IntlTelInputWidget(visible_input_attrs={
            'class': 'form-control',
        },
        preferred_countries=['us', 'ca']
    ),
```

In your first example you're setting a `preferred-countries` attribute on the input, instead of `data-preferred-countries`, which you do in the second example.

`preferred_countries` as a keyword argument (and with an underscore instead of hyphen) maps to `data-preferred-countries` when the input is rendered.

Hope that answers your question.

**Comment by KrunchMuffin** [comment]
Thanks Ben!

**Comment by KrunchMuffin** [comment]
I should have tried first. Doesn't appear to be working...

        widgets = {
            'company_phone': IntlTelInputWidget(visible_input_attrs={
                'class': 'form-control',
                }, prefered_countries=['us', 'ca']),

still getting

`data-prefered-countries="['us', 'gb']"`

**Comment by KrunchMuffin** [comment]
nevermind, misspelled `prefered`

**Comment by benmurden** [comment]
I'm sure it's happened to me more than once. :)

Glad to help. Closing this issue.
